import type { Product } from '../types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-neon-runner',
    name: 'Neon Runner Archive Pair',
    description: 'A boxed statement sneaker pair with reflective trim, bright sole detailing, and a clean unboxed presentation for the storefront.',
    category: 'Sneakers',
    priceRange: { min: 1499, max: 1799 },
    retailPrice: 1999,
    markdownPercentage: 25,
    discountPrice: 1499,
    confidenceScore: 96,
    imageUrl: 'https://picsum.photos/seed/quirkify-neon-runner/900/1200',
    imageUrls: [
      'https://picsum.photos/seed/quirkify-neon-runner/900/1200',
      'https://picsum.photos/seed/quirkify-neon-runner-side/900/1200',
      'https://picsum.photos/seed/quirkify-neon-runner-box/900/1200',
    ],
    status: 'approved',
    listingType: 'store',
    condition: 'Like New',
    stock: 3,
    totalStock: 3,
    allocations: { store: 3, auction: 0, packs: 0 },
    rarity: 'Rare',
    stats: { quirkiness: 89, rarity: 82, utility: 76, hype: 91 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    approvalDate: new Date().toISOString(),
    authorUid: 'demo-catalog',
    version: 1,
  },
  {
    id: 'demo-lilac-bomber',
    name: 'Lilac Transit Bomber',
    description: 'A lightweight bomber with tonal panels and a premium thrifted finish, positioned as a quick-turn hero item for featured drops.',
    category: 'Clothing',
    priceRange: { min: 899, max: 1099 },
    retailPrice: 1299,
    markdownPercentage: 31,
    discountPrice: 899,
    confidenceScore: 94,
    imageUrl: 'https://picsum.photos/seed/quirkify-lilac-bomber/900/1200',
    imageUrls: [
      'https://picsum.photos/seed/quirkify-lilac-bomber/900/1200',
      'https://picsum.photos/seed/quirkify-lilac-bomber-back/900/1200',
    ],
    status: 'approved',
    listingType: 'both',
    condition: 'Pre-owned',
    stock: 2,
    totalStock: 2,
    allocations: { store: 1, auction: 1, packs: 0 },
    rarity: 'Super Rare',
    stats: { quirkiness: 84, rarity: 88, utility: 68, hype: 86 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    approvalDate: new Date().toISOString(),
    authorUid: 'demo-catalog',
    version: 1,
  },
  {
    id: 'demo-arcade-headset',
    name: 'Arcade Pulse Headset',
    description: 'A glossy wired headset styled as a nostalgia-tech crossover piece, ideal for testing electronics cards and media-heavy detail pages.',
    category: 'Electronics',
    priceRange: { min: 749, max: 899 },
    retailPrice: 1099,
    markdownPercentage: 32,
    discountPrice: 749,
    confidenceScore: 93,
    imageUrl: 'https://picsum.photos/seed/quirkify-arcade-headset/900/1200',
    imageUrls: [
      'https://picsum.photos/seed/quirkify-arcade-headset/900/1200',
      'https://picsum.photos/seed/quirkify-arcade-headset-angle/900/1200',
    ],
    status: 'approved',
    listingType: 'store',
    condition: 'Refurbished',
    stock: 4,
    totalStock: 4,
    allocations: { store: 4, auction: 0, packs: 0 },
    rarity: 'Limited',
    stats: { quirkiness: 81, rarity: 73, utility: 88, hype: 78 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    approvalDate: new Date().toISOString(),
    authorUid: 'demo-catalog',
    version: 1,
  },
  {
    id: 'demo-collector-figure',
    name: 'Midnight Mascot Figure',
    description: 'A stylised collectible figure with display-box appeal, useful for testing rarity badges, collector language, and giftable stock cards.',
    category: 'Collectibles',
    priceRange: { min: 599, max: 799 },
    retailPrice: 899,
    markdownPercentage: 22,
    discountPrice: 0,
    confidenceScore: 91,
    imageUrl: 'https://picsum.photos/seed/quirkify-midnight-figure/900/1200',
    imageUrls: [
      'https://picsum.photos/seed/quirkify-midnight-figure/900/1200',
      'https://picsum.photos/seed/quirkify-midnight-figure-box/900/1200',
    ],
    status: 'approved',
    listingType: 'both',
    condition: 'New',
    stock: 6,
    totalStock: 6,
    allocations: { store: 4, auction: 2, packs: 0 },
    rarity: 'Unique',
    stats: { quirkiness: 92, rarity: 94, utility: 55, hype: 90 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    approvalDate: new Date().toISOString(),
    authorUid: 'demo-catalog',
    version: 1,
  },
  {
    id: 'demo-studio-tote',
    name: 'Studio Carry Tote',
    description: 'A soft-structured carry tote with contrast stitching and enough detail to test accessories merchandising across mobile and desktop layouts.',
    category: 'Accessories',
    priceRange: { min: 459, max: 599 },
    retailPrice: 699,
    markdownPercentage: 34,
    discountPrice: 459,
    confidenceScore: 90,
    imageUrl: 'https://picsum.photos/seed/quirkify-studio-tote/900/1200',
    imageUrls: [
      'https://picsum.photos/seed/quirkify-studio-tote/900/1200',
      'https://picsum.photos/seed/quirkify-studio-tote-open/900/1200',
    ],
    status: 'approved',
    listingType: 'store',
    condition: 'Like New',
    stock: 5,
    totalStock: 5,
    allocations: { store: 5, auction: 0, packs: 0 },
    rarity: 'Common',
    stats: { quirkiness: 72, rarity: 60, utility: 86, hype: 69 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    approvalDate: new Date().toISOString(),
    authorUid: 'demo-catalog',
    version: 1,
  },
];

export function isDemoProductId(id: string) {
  return DEMO_PRODUCTS.some((product) => product.id === id);
}
